version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 80:80
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - ./:/var/www/building
    links:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql.Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306